name: deploy

on:
  push:
    branches: [ main ]   # Deploy on commits to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v5

      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to godsimulator.github.io
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main    # branch in target repo (for GitHub Pages)
          folder: dist    # folder to deploy
          repository-name: godsimulator/godsimulator.github.io
          token: ${{ secrets.PAT }}
